### ISSUE TITLE
Create hashed and temporary token for local storage

### ISSUE THREAD

**Issue by n3a9** [hack4impact-uiuc/ymca#75]
One issue is that we're storing the token in local storage, which is relatively unsafe. Instead, hash the token and set an expiration time for it (for example, will expire after 1 hour) that will require the user to log in again. Shout out @yousefa00 for the idea 🤩

**Comment by yousefa00** [comment]
Ok, so here's how to do this. 

First, when you make the users account for the first time, you're going to generate a hash for them:
- You'll need to verify that the username doesn't exist already (you guys have probably already done this)
- Take their password and append an arbitrary length set of random characters (>8 preferably). These random characters are called a salt and they're used to prevent the rainbow table attack vector.
- Generate a hash by using a sha512 algorithm (find a library online) and pass the password and salt string you just made as your key
- Store the hash AND salt in a db where you map the username to this data (use a dictionary)

Next, we need to grant a user their token if the password is correct (have this done automatically after generating a hash if its their first time logging in, or ask them to log in again now that their account has been created):
- Query the database for the username the person submits
- Generate a new hash using their password with the appended salt from this query (remember, u stored this earlier)
- Check if this new hash equals the password hash stored in the database
- If it doesn't respond with an appropriate request otherwise return a token and set its expiration to 6hrs
         - This is how we did this step in JS at CompSci Kids: let token = jwt.sign({ username: username }, 
            config.secret, {expiresIn: "6hr});
- Store the token in the local storage on the front end

Validating token:
- When a request gets made you'll need to pass the token in as a Bearer in the Authorization header of your api request (pretty easy just look up how to do this)
- On the front end check if the token signature is valid (it will be invalid after 6 hours!!)
- If its invalid return an appropriate response that redirects the user to the login screen

ENJOY, your website authentication is now secure

**Comment by n3a9** [comment]
Turns out our token is already timed :) Thank you though @yousefa00!
